### ISSUE TITLE
Extends tag in docs is wrong

### ISSUE THREAD

**Issue by ashthornton-gc** [philicevic/mix-html-builder#10]
Took me quite a while to figure out why `<extend>` wasn't working as described in the docs. After making sure I was pulling in the master branch I eventually found out that the tag posthtml-extend is looking for was `<extends>`.

I think it'd be useful if you linked to the posthtml-extend docs in yours so people can see the extra functionality available.

Also, when are you planning on publishing the master branch version to npm? Would be nice to just include that rather than a master branch with no version number.

**Comment by philicevic** [comment]
Thank you, I don't really know how i messed that one up..

I planned to add #7 before releasing v0.5 and I'm not really satisfied with the solutions I used this far. If I don't get this to work properly soon I guess I'll release it without the feature.
