### ISSUE TITLE
Includes within layout html files

### ISSUE THREAD

**Issue by surgiie** [philicevic/mix-html-builder#12]
I can get includes to work fine if they are in my html files but if use an include within a layout.html file it does not compile successfully

It will just show up as `<include ....>` on the compiled file.

Is this not supported?

**Comment by philicevic** [comment]
Unfortunately it is not supported yet.

It could be a nice feature for the future, so I'm leaving this Issue open for now.

**Comment by surgiie** [comment]
@philicevic 

This works by registering the `posthtml-include` as a plugin with `posthtml-extend` in your HtmlBuilder `webpackRules()` function:

```js
const include = require('posthtml-include')({
    root: this.partialRoot,
 })
....
require('posthtml-extend')({
    root: this.layoutRoot,
    plugins: [ include]
})
```

**Comment by philicevic** [comment]
Thanks a lot, @surgiie!
