### ISSUE TITLE
How do I configure `posthtml-extend` options?

### ISSUE THREAD

**Issue by angelinetran** [philicevic/mix-html-builder#13]
I would like to set the `posthtml-extend` `strict` option to `false`. https://github.com/posthtml/posthtml-extend#strict

I'm getting the error below when I have a missing block in my layout.html file. This is causing BrowserSync to fail. When I add the missing block, I need to restart my `npm run watch` command. I'm hoping that being able to set the option will help me avoid this error.

```
Html Webpack Plugin:
  Error: Child compilation failed:
  Module build failed (from ./node_modules/posthtml-loader/lib/index.js):
  PostHTML Loader: 
  [posthtml-extend] Unexpected block "title"
```

**Comment by philicevic** [comment]
Thanks for your pull request!
I changed it up a bit but you will be able to configure both posthtml plugins via the `postHtmlConfig` option, like this in your example:

```
postHtmlConfig: {
    extend: {
        strict: false
    }
}
```

This will be available in v0.6
