### ISSUE TITLE
output + mix.setPublicPath + inject

### ISSUE THREAD

**Issue by goaround** [philicevic/mix-html-builder#16]
I'm going in 404 circles...

I would like to place all public files in `/public` therefore I've defined `mix.setPublicPath('public')`

The problem is now I never get the right path to my css/js files with `inject: true`

If I set `output: 'dist'` as of the default settings my html file will land in `/public/dist/index.html` with `<link href="app.css" rel="stylesheet">` but the app.css file is in `/public/app.css`  => 404

If I place the css/js files with Mix in dist `mix.js('src/js/app.js', 'dist')` the injected path in the `/public/dist/index.html` file will be `dist/app.css` => `/public/dist/dist/app.css` => 404

The perfect setting would be `output: ''` but because `!input.output`is true https://github.com/philicevic/mix-html-builder/blob/master/mix-html-builder.js#L16 it will take the default setting `'dist'` and I have the same result => 404

I think the default setting has to be `output: ''` not `dist`

**Comment by goaround** [comment]
I found a workaround `output: '../public'` but its not very pleasant

**Comment by philicevic** [comment]
Fixed in v0.6.1

`output` now allows an empty string as its input value.
