### ISSUE TITLE
Include does not work after block in layout

### ISSUE THREAD

**Issue by weblabio** [philicevic/mix-html-builder#17]
**mix-html-builder:** ^0.6.1
**laravel-mix:** ^5.0.1

_home.html_
```html
<extends src="default.html">
    <block name="content">
        <h1>Welcome!</h1>
    </block>
</extends>
```

layouts/default.html
```html
<include src="header.html"></include>

<block name="content" />

<include src="footer.html"></include>
```

_partials/header.html_
```html
<header>HEADER</header>
```

_partials/footer.html_
```html
<footer>FOOTER</header>
```

**Problem:**
footer.html - not displayed if located after `<block />`

![image](https://user-images.githubusercontent.com/24838013/86594027-fab31600-bf9e-11ea-8639-e95d1a1158c9.png)

if moved to block:
```html
<include src="header.html"></include>
<include src="footer.html"></include>

<block name="content" />
```

then the part is displayed:
![image](https://user-images.githubusercontent.com/24838013/86594118-23d3a680-bf9f-11ea-87d4-6d94db509b51.png)

there are no errors in the console:
![image](https://user-images.githubusercontent.com/24838013/86594452-b7a57280-bf9f-11ea-9c66-a65c33711938.png)

**Comment by WebLab-ImpCode** [comment]
if you use a closing tag, then everything works
```html
<block name="content"></block>
```
at least you need to fix the example in the documentation
![image](https://user-images.githubusercontent.com/24838013/86594871-73ff3880-bfa0-11ea-88c9-132a57661e94.png)
