### ISSUE TITLE
Multiple layouts extends

### ISSUE THREAD

**Issue by weblabio** [philicevic/mix-html-builder#18]
Tell me, please, is it possible to use templates in this way?

_home.html_
```html
<extends src="default">
   <block name="content">Home Page</block>
</extends>
```

_layouts/default.html_
```html
<extends src="app">
   <block name="layout">
        <header>...</header>
        <main>
            <block name="content" />
        </main>
       <footer>...</footer>
   </block>
</extends>
```

_layouts/app.html_
```html
<head>...</head>
<body>
     <block name="layout" />
</body>
```

_home -> layouts/default -> layouts/app_
so you can use many intermediate layers instead of layouts/default and having a basic immutable layer (layouts/app)

Now, if I use the code above, I get an error:
**[posthtml-extend] Unexpected block "content"**

If I rename **layout** to **content** inside _layouts/app.html_
then the contents of _layouts/default.html_ is ignored

my solution looks dirty, such a template should be in every page, layout **default** can be changed for individual pages:
```html
<include src="start.html" locals='{
    "pageTitle": "HomePage",
    "pageClass": "page-home"
}'></include>

<extends src="default.html">
    <block name="content">
        <h1>Welcome!</h1>
    </block>
</extends>

<include src="end.html"></include>
```

**Comment by philicevic** [comment]
I don't think that i can do much about it, as the functionality depends on posthtml-extend. If anyone finds a way to do this, feel free to open a PR.
But I myself won't try to implement this right now.
