### ISSUE TITLE
Tags are truncated/moved in the build

### ISSUE THREAD

**Issue by weblabio** [philicevic/mix-html-builder#20]
_home.html_
```html
<include src="start.html" locals='{
    "pageTitle": "HomePage",
    "pageClass": "page-home"
}'></include>

<extends src="default.html">
    <block name="content">
        <h1>Welcome!</h1>
    </block>
</extends>

<include src="end.html"></include>
```

_partials/start.html_
```html
<!doctype html>
<html lang="en">
<head>
    ....
    <title>PlushHouse » {{ pageTitle }}</title>
</head>
<body class="{{ pageClass }}">
```

_partials/end.html_
```html
<script src="/js/app.js"></script>
</body>
</html>
```

Tags  `</body></html>`  are truncated/moved in the build home.html:
![image](https://user-images.githubusercontent.com/24838013/86626108-e6870d00-bfce-11ea-8cf5-0089fa7ed3be.png)

Perhaps this is the result of the optimizer, is it possible to configure this behavior?

**Comment by philicevic** [comment]
Unfortunatly it seems that this is a behaviour of posthtml that i can't customize.
But it should be better practice to close tags in the same partial where you opened them.
