### ISSUE TITLE
Laravel mix 6 support

### ISSUE THREAD

**Issue by kevinruscoe** [philicevic/mix-html-builder#24]
Version 6 of mix is right around the corner, currently this doesn't seem to do anything with the latest beta (14). Is there's plans to support version 6?

**Comment by philicevic** [comment]
I'll definitely try to support laravel-mix v6. Not quite sure, when I will get started on this (as for the other open issues), but it is planned.

Leaving this open to add it to a milestone.

**Comment by kevinruscoe** [comment]
Just pinging to let you know laravel-mix v6 is now out.
