### ISSUE TITLE
How can there be included multiple html files?

### ISSUE THREAD

**Issue by altinmullaidrizi** [philicevic/mix-html-builder#43]
Is there a way to include multiple HTML files, for example instead of just index.html, I want to bundle the about.html into the public folder as well and be able to visit it with localhost:3000/about.html.

**Comment by philicevic** [comment]
I suggest you read the documentation 😉 

From [docs](https://github.com/philicevic/mix-html-builder#usage):

Available options -> htmlRoot -> "Your html root file. **You can also use glob patterns to use multiple files**."
