### ISSUE TITLE
Add possibility to pass data into a partial

### ISSUE THREAD

**Issue by philicevic** [philicevic/mix-html-builder#7]
While using a partial, users should be able to pass data into it.

Example:

Parent file:
```
<include src="partial.html" data='{"field": "value"}' />
```

Partial:

```
<var name="field" />
// or
{{ field }}
```

Unfortunately [posthtml-include](https://github.com/posthtml/posthtml-include) doesn't support this at the moment, so I'm in search for another solution.

**Comment by ashthornton-gc** [comment]
+1 for this.

Scope in [posthtml-expressions](https://github.com/posthtml/posthtml-expressions#scopes) might be useful here

**Comment by philicevic** [comment]
Update:

I created a pull request in `posthtml-include` to add this feature:
https://github.com/posthtml/posthtml-include/pull/35

This would fix this issue already.

**Comment by ashthornton-gc** [comment]
I've actually been experimenting with this today and ended up porting the posthtml-include logic into posthtml-expressions so it can link up with the `{{ }}` replacement already built in. Then adding a check for an extra `<data>` tag in the posthtml tree walk.

The syntax I went for looks like this:

```
<include src="test.html">
   <data key="heading">A heading</data>
   <data key="text">Some text</data>
</include>
```

test.html:
```
<h1>{{ heading : Default heading }}</h1>
<p>{{ text: Default text }}</p>
```

I tweaked the placeholder check to use a default value delimited by ` : `

**Comment by philicevic** [comment]
My pull request was merged today and the feature is now available only by updating `posthtml-include`.

@ashthornton-gc I really like the simple option to pass a default value, have you thought about creating a pull request for the `posthtml-expressions` package? I think this would be a nice addition even though it already supports the use of [conditions](https://github.com/posthtml/posthtml-expressions#conditionals).
