### ISSUE TITLE
extend — not work

### ISSUE THREAD

**Issue by pfrlv** [philicevic/mix-html-builder#8]
Hi!
I have the <extend> section after build in all builded html files. 

```
.html({
    output: 'public',
    htmlRoot: 'src/html/views/*.html',
    partialRoot: 'src/html/includes',
    layoutRoot: 'src/html/layouts',
    minify: {
      collapseWhitespace: true,
      removeAttributeQuotes: true,
      removeComments: true
    }
  })

**Comment by philicevic** [comment]
Hey!
Are you using a released version of the package or the current master?
Layouts are not yet released in any version. They will be released in 0.5.0.

That means that at the moment you can only use them if you are using the current master.
