### ISSUE TITLE
Glob htmlRoot folder/directory

### ISSUE THREAD

**Issue by bigskillet** [philicevic/mix-html-builder#9]
How might glob folders using htmlRoot? For example, when I use `htmlRoot: './src/*.html'` with `index.html` and `about.html`, it works fine. If I put the `about.html` in a folder, like `/about/index.html` and then use htmlRoot: `./src/**/*.html`, it doesn't work.

Is it possible to do this with `mix-html-builder`? If not, is there some other method I could use?

**Comment by philicevic** [comment]
Right now this is not possible with `mix-html-builder`. I'm not sure if you could do this using a workaround.

However, this should definitely be possible in the future, so I will work on it.
